---
kind: pipeline
name: build
type: kubernetes

trigger:
  branch:
  - master
  event:
  - push

steps:
- name: build-image
  image: plugins/docker
  settings:
    registry: harbor.mark.eek
    username: 
      from_secret: harbor_username
    password: 
      from_secret: harbor_password
    repo: harbor.mark.eek/library/sensor-exporter
    dockerfile: Dockerfile
    tags: 
    - ${DRONE_COMMIT}
    - "ts-${DRONE_BUILD_CREATED}"
    - latest
    insecure: true
    mtu: 1400

